Feature/fdp 1673 spotless
OSGP/sng-crest-device-service pull request #28
Opened 2024-04-17 06:59 UTC by loesimmens

2024-04-17 08:20 UTC, jasperkamerling requested changes

2024-04-17 08:20 UTC, jasperkamerling commented on build.gradle.kts
> +        dependsOn(tasks.withType<GenerateAvroJavaTask>())
Waarom is deze hier nu nodig en bij de andere projecten niet?

2024-04-17 08:26 UTC, loesimmens commented on build.gradle.kts
> +        dependsOn(tasks.withType<GenerateAvroJavaTask>())
Daar kom ik niet helemaal achter. In main was het ook niet nodig, dus ik ben bang dat het formatteren dit heeft veroorzaakt, maar ik kan niet achterhalen waar of waarom.

2024-05-29 09:09 UTC, jasperkamerling requested changes

2024-05-29 09:09 UTC, jasperkamerling commented on build.gradle.kts
> +        dependsOn(tasks.withType<GenerateAvroJavaTask>())
Deze dependency graag nog verplaatsen naar de application module

2024-05-29 09:10 UTC, jasperkamerling approved these changes

2024-05-29 09:12 UTC, jasperkamerling requested changes

2024-05-29 09:12 UTC, jasperkamerling commented on build.gradle.kts
> +                    .trimIndent(),
Graag opnemen in een file zoals bij de `sng-io-file-processor`

2024-05-29 09:55 UTC, sanderv approved these changes

2024-05-29 11:14 UTC, merged