FDP-2306: handle failure urcs better
OSGP/sng-crest-device-service pull request #31
Opened 2024-05-29 15:07 UTC by loesimmens

2024-05-30 06:55 UTC, jasperkamerling requested changes

2024-05-30 06:55 UTC, jasperkamerling commented on application/src/main/kotlin/org/gxf/crestdeviceservice/coap/UrcService.kt
> +                null -> "Unknown URC"
I would expect these error descriptions in the `PskOrDownlinkErrorUrc` class

2024-05-30 06:55 UTC, jasperkamerling commented on application/src/main/kotlin/org/gxf/crestdeviceservice/coap/UrcService.kt
> +            .forEach { urc -> handlePskOrDownlinkError(identity, urc) }
We can only call the `handlePskOrDownlinkError` function once. Otherwise we will hit the `!pskService.isPendingKeyPresent(identity)` check and see that the pending key is no longer present.

It would be better to send all the downlink errors to the `handlePskOrDownlinkError` function.

2024-05-30 06:55 UTC, jasperkamerling commented on application/src/main/kotlin/org/gxf/crestdeviceservice/coap/UrcService.kt
> +        PskOrDownlinkErrorUrc.entries.toTypedArray().contains(PskOrDownlinkErrorUrc.from(urc))
This function could move to the `PskOrDownlinkErrorUrc` class.
I also think the `toTypedArray()` and casting it to an error object are necessary.

2024-05-30 06:55 UTC, jasperkamerling commented on application/src/test/kotlin/org/gxf/crestdeviceservice/coap/UrcServiceTest.kt
> +    fun shouldSetPendingKeyAsInvalidWhenFailureURCReceived(urc: String) {
Ik zou graag ook nog een test zien met meerdere downlinks. En wat er gebeurt als we de onverwachte "TS:ERR" Foutmelding ontvangen.

2024-05-30 08:13 UTC, loesimmens commented on application/src/main/kotlin/org/gxf/crestdeviceservice/coap/UrcService.kt
> +        PskOrDownlinkErrorUrc.entries.toTypedArray().contains(PskOrDownlinkErrorUrc.from(urc))
verplaatst en versimpeld

2024-05-30 15:04 UTC, smvdheijden requested changes

2024-05-30 15:04 UTC, smvdheijden commented on application/src/test/kotlin/org/gxf/crestdeviceservice/coap/UrcServiceTest.kt
> +                listOf("INIT"),
This list could also include similar errors as the above list, but with a different prefix, like for example: `MSI:DLNA`.

2024-05-31 08:25 UTC, loesimmens commented on application/src/main/kotlin/org/gxf/crestdeviceservice/coap/PskOrDownlinkErrorUrc.kt
> +    DL_CSER("[DL]:CSER", "Checksum error");
Good catch!

2024-05-31 08:42 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/crestdeviceservice/coap/PskOrDownlinkErrorUrc.kt
> +    DL_CSER("[DL]:CSER", "Checksum error");
Not sure, but I think not, if an unknown downlink command was returned, that would probably not be a `PSK` command :wink: 
Furthermore, `PSK:#ERR` is probably also not relevant. (The `#` is probably also a placeholder, in the specs it is annotated with `# = Only for AKB V/I/P`, whatever that means...)

2024-05-31 08:53 UTC, jasperkamerling approved these changes

2024-05-31 09:00 UTC, smvdheijden approved these changes

2024-05-31 09:01 UTC, merged