FDP-2359: command handling reboot
OSGP/sng-crest-device-service pull request #39
Opened 2024-08-22 12:42 UTC by loesimmens

2024-09-04 10:21 UTC, sanderv requested changes

2024-09-04 10:21 UTC, sanderv commented on application/src/main/kotlin/org/gxf/crestdeviceservice/model/ErrorUrc.kt
> +    UNK("UNK", "Downlink unknown"),
Hier is de `code` gelijk aan de `<enum>.name()`, ik zou óf de enums anders noemen of de `code` weglaten

2024-09-04 10:21 UTC, sanderv commented on application/src/main/kotlin/org/gxf/crestdeviceservice/service/DownlinkService.kt
> +    var downlinkCumulative = ""
In een service mag je geen state bijhouden

2024-09-04 10:21 UTC, sanderv commented on application/src/main/kotlin/org/gxf/crestdeviceservice/service/DownlinkService.kt
> +        val currentSize = Ascii85.encode(downlinkCumulative.toByteArray()).toByteArray().size
```suggestion
        val currentSize = Ascii85.encode(downlinkCumulative.toByteArray()).length
```
Kan dat ook?

2024-09-04 10:21 UTC, sanderv commented on application/src/main/kotlin/org/gxf/crestdeviceservice/service/DownlinkService.kt
> +    fun fitsInMaxMessageSize(downlinkToAdd: String): Boolean {
Het leest als een simpele boolean check, maar de functie heeft ook side-effects, kun je dat in de naam terug laten komen?

2024-09-04 10:21 UTC, sanderv commented on application/src/main/kotlin/org/gxf/crestdeviceservice/controller/MessageController.kt
> +                val downlink = downlinkService.getDownlinkForDevice(identity, body)
Als ik de code volg, dan is dit een gewone string, nog niet Base85 encoded

2024-09-04 10:28 UTC, sanderv commented on application/src/main/kotlin/org/gxf/crestdeviceservice/controller/MessageController.kt
> +                val downlink = downlinkService.getDownlinkForDevice(identity, body)
Verkeerd-om gedacht: we hoeven commands niet base85 te encoden

2024-09-04 12:57 UTC, loesimmens commented on application/src/main/kotlin/org/gxf/crestdeviceservice/service/DownlinkService.kt
> +    var downlinkCumulative = ""
Downlink class aangemaakt

2024-09-04 13:21 UTC, smvdheijden requested changes

2024-09-04 13:21 UTC, smvdheijden commented on application/src/test/kotlin/org/gxf/crestdeviceservice/service/DownlinkServiceTest.kt
> +        val downlinkExisting = "!CMD:REBOOT;!CMD:REBOOT"
Do we need to put an exclamation mark before each command or just before a downlink?

2024-09-04 13:26 UTC, loesimmens commented on application/src/main/avro/CommandFeedback.avsc
> +          "Cancelled"
will fix :)

2024-09-04 13:36 UTC, loesimmens commented on application/src/main/kotlin/org/gxf/crestdeviceservice/service/DownlinkService.kt
> +    var downlinkCumulative = ""
removed

2024-09-04 13:37 UTC, loesimmens commented on settings.gradle.kts
> +            library("ascii85", "com.github.fzakaria", "ascii85").versionRef("ascii85")
removed

2024-09-04 14:59 UTC, loesimmens commented on application/src/main/kotlin/org/gxf/crestdeviceservice/command/service/CommandFeedbackService.kt
> +    }
refactored

2024-09-04 15:03 UTC, loesimmens commented on application/src/test/kotlin/org/gxf/crestdeviceservice/service/DownlinkServiceTest.kt
> +        val downlinkExisting = "!CMD:REBOOT;!CMD:REBOOT"
good catch

2024-09-05 13:17 UTC, loesimmens commented on application/src/main/kotlin/org/gxf/crestdeviceservice/service/DownlinkService.kt
> +            pskService.readyForPskSetCommand(command.deviceId)
fixed together

2024-09-05 13:31 UTC, loesimmens commented on application/src/main/resources/db/migration/V6__command.sql
> +create table command
maybe not in this pr

2024-09-05 13:31 UTC, loesimmens commented on application/src/main/resources/db/test-data/V7__command_test_data.sql
> +insert into command (id, device_id, correlation_id, timestamp_issued, type, command_value, status)
maybe not in this pr

2024-09-05 13:32 UTC, loesimmens commented on application/src/main/kotlin/org/gxf/crestdeviceservice/command/service/CommandService.kt
> +    fun shouldBeRejected(command: ExternalCommand): Optional<String> {
I did this anyway ;)

2024-09-05 14:22 UTC, loesimmens commented on application/src/main/kotlin/org/gxf/crestdeviceservice/service/UrcService.kt
> +            return parts.all { part -> downlink.contains(part) }
Refactored a bit, but without regex. Do you have a regex suggestion that improves on this?

2024-09-09 12:17 UTC, sanderv approved these changes

2024-09-10 09:48 UTC, smvdheijden requested changes

2024-09-10 09:48 UTC, smvdheijden commented on application/src/test/kotlin/org/gxf/crestdeviceservice/command/mapper/CommandMapperTest.kt
> +            .isEqualTo(expectedException)
I think I might prefer one of these possible alternatives without using recursive comparison:

- with checks on type and message:
```kotlin
        assertThatThrownBy { CommandMapper.externalCommandToCommandEntity(externalCommand, status) }
            .isInstanceOf(CommandValidationException::class.java)
            .hasMessage("Command unknown: ${externalCommand.command}")
```
- with (likely) increased readability:
```kotlin
        assertThatExceptionOfType(CommandValidationException::class.java)
            .isThrownBy { CommandMapper.externalCommandToCommandEntity(externalCommand, status) }
            .withMessage("Command unknown: ${externalCommand.command}")
```

- with a clearer distinction between "act" and "assert":
```kotlin
        val actual = catchThrowable {
            CommandMapper.externalCommandToCommandEntity(externalCommand, status)
        }

        assertThat(actual)
            .isInstanceOf(CommandValidationException::class.java)
            .hasMessage("Command unknown: ${externalCommand.command}")
```

2024-09-10 09:48 UTC, smvdheijden commented on application/src/test/kotlin/org/gxf/crestdeviceservice/command/mapper/CommandMapperTest.kt
> +            .isInstanceOf(IllegalArgumentException::class.java)
You could even reduce this to:
```kotlin
        assertThatIllegalArgumentException().isThrownBy {
            CommandMapper.commandNameToType("invalid")
        }
``` 

or more verbose with a clearer distinction between the "triple A" sections ("arrange, "act", and "assert")
```kotlin
    val commandName = "invalid"

    val actual = catchThrowable { CommandMapper.commandNameToType(commandName) }

    assertThat(actual).isInstanceOf(IllegalArgumentException::class.java)

2024-09-10 13:23 UTC, loesimmens commented on application/src/test/kotlin/org/gxf/crestdeviceservice/command/mapper/CommandMapperTest.kt
> +            .isEqualTo(expectedException)
mooier inderdaad

2024-09-10 14:26 UTC, smvdheijden approved these changes

2024-09-10 14:40 UTC, merged