Feature/fdp 1687
OSGP/sng-crest-device-service pull request #5
Opened 2023-10-31 09:39 UTC by LucianoFavoroso

2023-10-31 10:11 UTC, jasperkamerling requested changes

2023-10-31 10:11 UTC, jasperkamerling commented on settings.gradle.kts
> -include("components:kafka")
Graag de module wat functionelere noemen dan avro

2023-10-31 10:11 UTC, jasperkamerling commented on components/avro/src/main/avro/Measurement.avsc
> +  "namespace": "org.gxf.crestdeviceservice",
De message gaat over verschillende services heen dus die zal ook een generiekere namespace nodig hebben.

2023-10-31 10:11 UTC, jasperkamerling commented on application/src/main/kotlin/org/gxf/crestdeviceservice/kafka/MessageProcessorConsumer.kt
> +class MessageProcessorConsumer {
We gaan hier geen measurements consumen

2023-11-01 08:01 UTC, sanderv commented on application/src/integrationTest/resources/application.yaml
> +      id: "gxf-sng-crest-device-service"
waar wordt deze gebruikt? In de properties class is dit een ongebruikt field

2023-11-01 08:04 UTC, jasperkamerling commented on application/src/main/kotlin/org/gxf/crestdeviceservice/CrestDeviceServiceApplication.kt
> +@EnableConfigurationProperties(KafkaProducerProperties::class)
Dan heb je wel de `@ConfigurationPropertiesScan` annotatie nodig op je application.

2023-11-01 08:11 UTC, LucianoFavoroso commented on application/src/main/kotlin/org/gxf/crestdeviceservice/CrestDeviceServiceApplication.kt
> +@EnableConfigurationProperties(KafkaProducerProperties::class)
In een ander PR werd mij gevraagd om het zo te doen. Welke methode gaan wij aanhouden?

2023-11-02 09:26 UTC, sanderv commented on application/src/main/kotlin/org/gxf/crestdeviceservice/CrestDeviceServiceApplication.kt
> +@EnableConfigurationProperties(KafkaProducerProperties::class)
We houden de Spring-manier aan: convention over configuration, dus `@ConfigurationPropertiesScan` over `@EnableConfigurationProperties(...)`

2023-11-02 09:30 UTC, sanderv approved these changes

2023-11-02 09:31 UTC, sanderv commented
Jasper is ziek, maar z'n punten zijn verwerkt. Ik force-merge deze PR

2023-11-02 09:31 UTC, merged