FDP-2551: Implement sending firmware update to device
OSGP/sng-crest-device-service pull request #53
Opened 2024-10-03 13:15 UTC by sanderv

2024-10-10 11:33 UTC, loesimmens requested changes

2024-10-10 11:33 UTC, loesimmens commented on components/psk/src/main/kotlin/org/gxf/crestdeviceservice/psk/service/PskService.kt
>      fun getCurrentReadyPsk(deviceId: String): PreSharedKey? {
hier ook de NoExistingPskException gooien?

2024-10-10 11:33 UTC, loesimmens commented on application/src/test/kotlin/org/gxf/crestdeviceservice/controller/PskControllerTest.kt
> +import org.mockito.kotlin.*
opslitsen in losse imports

2024-10-10 11:33 UTC, loesimmens commented on application/src/test/kotlin/org/gxf/crestdeviceservice/service/DownlinkServiceTest.kt
> +import org.mockito.kotlin.*
imports opsplitsen

2024-10-10 11:33 UTC, loesimmens commented on components/base85/README.md
> +Supports [RFC 1924](https://tools.ietf.org/html/rfc1924), [Z85](https://rfc.zeromq.org/spec:32/Z85/), and [Ascii85](https://en.wikipedia.org/wiki/Ascii85) (with optional null and space compression).
Alleen RFC 1924, toch?

2024-10-10 11:33 UTC, loesimmens commented on components/firmware/src/test/kotlin/org/gxf/crestdeviceservice/firmware/entity/FirmwareFactory.kt
> +import java.util.*
imports splitsen

2024-10-10 11:33 UTC, loesimmens commented on components/firmware/src/test/kotlin/org/gxf/crestdeviceservice/firmware/entity/FirmwarePacketTest.kt
> +import java.util.*
imports splitsen

2024-10-10 11:33 UTC, loesimmens commented on components/firmware/src/test/resources/firmware-oneliner.txt
> +Bastiaan & Jeffrey
?

2024-10-10 11:33 UTC, loesimmens commented on components/firmware/src/main/kotlin/org/gxf/crestdeviceservice/firmware/service/FirmwareHashService.kt
> +internal class InternalFirmwareHashService : FirmwareHashService {
Internal?

2024-10-10 11:33 UTC, loesimmens commented on components/firmware/src/main/kotlin/org/gxf/crestdeviceservice/firmware/service/FirmwareHashService.kt
> +        val command = packet.substring(0, OTA_START.length)
```suggestion
        val command = OTA_START
```

2024-10-23 08:49 UTC, sanderv commented on components/firmware/src/main/kotlin/org/gxf/crestdeviceservice/firmware/service/FirmwareHashService.kt
> +internal class InternalFirmwareHashService : FirmwareHashService {
Seemed like a good idea at the time... Removed

2024-10-23 11:09 UTC, sanderv commented on application/src/main/kotlin/org/gxf/crestdeviceservice/consumer/IncomingDeviceCredentialsConsumer.kt
> +        commandService.save(listOf(pskCommand, pskSetCommand))
Combining also changes the return type for single params to a list of objects, unwanted side effect. I do like the vararg when calling a function, so changed it from List<> to vararg

2024-10-23 11:28 UTC, sanderv commented on application/src/main/kotlin/org/gxf/crestdeviceservice/service/DownlinkService.kt
> +    private fun fillDownlinkFromCommands(pendingCommands: List<Command>, downlink: Downlink) {
The downlink is filled by calling `addIfPossible(...)`

2024-10-23 11:35 UTC, sanderv commented on application/src/main/kotlin/org/gxf/crestdeviceservice/service/PayloadService.kt
> +                val firmware = firmwareService.findByName(firmwareCommand.commandValue!!)
The error is already in the `Command.init {}`, so this "should never happen"

2024-10-23 11:39 UTC, sanderv commented on application/src/main/kotlin/org/gxf/crestdeviceservice/service/command/CommandGenerator.kt
> +package org.gxf.crestdeviceservice.service.command
Moved the generators to that package

2024-10-23 11:55 UTC, sanderv commented on components/base85/README.md
> +Supports [RFC 1924](https://tools.ietf.org/html/rfc1924), [Z85](https://rfc.zeromq.org/spec:32/Z85/), and [Ascii85](https://en.wikipedia.org/wiki/Ascii85) (with optional null and space compression).
This is the original README, included as-is. Not sure what to do here

2024-10-24 07:09 UTC, levi-h approved these changes

2024-10-28 10:33 UTC, loesimmens requested changes

2024-10-28 10:33 UTC, loesimmens commented on components/firmware/src/main/kotlin/org/gxf/crestdeviceservice/firmware/service/FirmwareService.kt
> +@Service
Comparison seems to be with an older version of main. Will merging this pr overwrite te existing function `processFirmware` in main? See https://github.com/OSGP/sng-crest-device-service/blob/main/components/firmware/src/main/kotlin/org/gxf/crestdeviceservice/firmware/service/FirmwareService.kt

2024-10-28 12:40 UTC, loesimmens approved these changes

2024-10-28 12:50 UTC, merged