FDP-2571: added endpoints to add RSP and RSP2 commands for device
OSGP/sng-crest-device-service pull request #58
Opened 2024-10-16 12:21 UTC by levi-h

2024-10-16 12:48 UTC, loesimmens requested changes

2024-10-16 12:48 UTC, loesimmens commented on application/src/main/kotlin/org/gxf/crestdeviceservice/command/entity/Command.kt
> +        RSP("CMD:RSP", listOf("CMD:RSP"), listOf("DLER")),
I wonder whether the success and error URCs will work like this. In the case of success because they will not send a real success URC but rather the command/downlink sent by us (i.e. "CMD:RSP"), which is not in the same field in the message as the real URC codes. @sanderv how did you handle this for firmware? In the case of the error, I wonder if the URC will be "DLER" or "SOMETHING:DLER", like in the case of PSK, but I don't know if the RSP commands have a "prefix" like the PSK commands do.

2024-10-16 12:48 UTC, loesimmens commented on application/src/main/kotlin/org/gxf/crestdeviceservice/command/service/CommandService.kt
> +    open fun save(command: Command) {
why open?

2024-10-16 12:48 UTC, loesimmens commented on application/src/main/kotlin/org/gxf/crestdeviceservice/controller/RspController.kt
> +    @PostMapping("rsp/{deviceId}/test")
Did you test this locally? I think it will not work right now, because of the mutual TLS configured on the crest device service. In my branch, I'm adding a second server that does not use mutual TLS, but only the endpoints starting with "/web" will not require mutual TLS.

2024-10-16 12:48 UTC, loesimmens commented on application/src/test/kotlin/org/gxf/crestdeviceservice/controller/RspControllerTest.kt
> +            .perform(post("/rsp/device-id/test")) //
For clarity, use $DEVICE_ID instead of "device-id"

2024-10-16 12:48 UTC, loesimmens commented on application/src/test/kotlin/org/gxf/crestdeviceservice/controller/RspControllerTest.kt
> +            .perform(post("/rsp2/device-id/test")) //
For clarity, use $DEVICE_ID instead of "device-id"

2024-10-16 12:48 UTC, loesimmens commented on application/src/test/kotlin/org/gxf/crestdeviceservice/service/UrcServiceTest.kt
> +    fun handleSuccessUrcForRspCommand() {
This seems like a copy of the function above it. Did you mean to write a test about an rsp command?

2024-10-16 12:50 UTC, levi-h commented on application/src/main/kotlin/org/gxf/crestdeviceservice/command/entity/Command.kt
> +        RSP("CMD:RSP", listOf("CMD:RSP"), listOf("DLER")),
Initially, I left the success URC list empty, but then I saw the PSK:SET one. I agree that the error will probably be CMD:DLER.

2024-10-16 12:51 UTC, levi-h commented on application/src/main/kotlin/org/gxf/crestdeviceservice/command/service/CommandService.kt
> +    open fun save(command: Command) {
I forgot to remove that. I thought it was needed for Mockito

2024-10-16 12:53 UTC, levi-h commented on application/src/test/kotlin/org/gxf/crestdeviceservice/service/UrcServiceTest.kt
> +    fun handleSuccessUrcForRspCommand() {
I did, and then decided it wouldn't add much since there is no new behaviour here. I'll remove that together with the `open`.

2024-10-16 13:39 UTC, loesimmens approved these changes

2024-10-17 07:27 UTC, LucianoFavoroso approved these changes

2024-10-17 11:18 UTC, merged