FDP-2684: introduced device, moved secret from PSK to device
OSGP/sng-crest-device-service pull request #60
Opened 2024-10-22 13:22 UTC by levi-h

2024-10-23 08:02 UTC, sanderv approved these changes

2024-10-24 09:54 UTC, loesimmens requested changes

2024-10-24 09:54 UTC, loesimmens commented on components/device/src/main/kotlin/org/gxf/crestdeviceservice/device/exception/NoSuchDeviceException.kt
> +class NoSuchDeviceException(id: String) : Exception("Duplicate device: $id")
message nog even aanpassen

2024-10-24 10:00 UTC, loesimmens approved these changes

2024-10-24 10:02 UTC, merged