Feature/fdp 1628
OSGP/sng-crest-device-service pull request #7
Opened 2023-11-14 09:49 UTC by LucianoFavoroso

2023-11-21 10:48 UTC, JelleHoffman reviewed
There are still Sonar Encryption errors?

2023-11-21 11:00 UTC, JelleHoffman approved these changes
Sonar issues are false postives, therefore approved

2023-11-21 12:58 UTC, sanderv commented on application/src/main/kotlin/org/gxf/crestdeviceservice/psk/PskService.kt
> +        val allowedChars = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
Deze kan ook als constant

2023-11-23 10:43 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/crestdeviceservice/data/convertors/DatabaseFieldEncryptor.kt
> +        val cipher = Cipher.getInstance(ENCRYPTION_METHOD)
This looks like a false positive? 
Does it also fail when using the string directly, instead of using the constant?

2023-11-23 16:45 UTC, smvdheijden requested changes
- Add license headers!!!
- Use AssertJ assertions

2023-11-23 16:45 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/crestdeviceservice/coap/CoapMessageController.kt
> +class CoapMessageController(private val messageService: MessageService, private val downlinkService: DownlinkService) {
Should we make it the responsibility of the controller to check for downlinks? Or should it be the responsibility of the messageService?

2023-11-23 16:45 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/crestdeviceservice/data/entity/PskKey.kt
> +    constructor() : this(null, null)
- Should the parameters be nullable?
- Is the constructor needed?

2023-11-23 16:45 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/crestdeviceservice/psk/PskService.kt
> +        private const val KEY_LENGTH = 16L
According to the documentation the length should be _at least_ 16 characters. 
The documentation however does not (yet?) specify a maximum...
Probably not needed now, but maybe we should consider making this constant configurable?

2023-11-23 16:45 UTC, smvdheijden commented on application/src/main/resources/application-dev.yaml
> +    url: "jdbc:postgresql://localhost:5432/crest-device-service-test"
Consider using `-dev` suffix instead of `-test`.

2023-11-23 16:45 UTC, smvdheijden commented on application/src/main/resources/application-dev.yaml
> +    dev-device-identity: "867787050253370" #Should be the same as the identity in the simulator only relevant for dev
```suggestion
    # Initial PSK should be the same as the PSK in the simulator, only relevant for dev
    initial-psk: "ABCDEFGHIJKLMNOP" 
    # Device identity should be the same as the identity in the simulator, only relevant for dev
    device-identity: "867787050253370" 
```

2023-11-23 16:45 UTC, smvdheijden commented on application/src/test/kotlin/DownlinkServiceTest.kt
Move class to package `org.gxf.crestdeviceservice.coap`

2023-11-23 16:45 UTC, smvdheijden commented on application/src/test/kotlin/DownlinkServiceTest.kt
> +import org.gxf.crestdeviceservice.coap.DownlinkService
Import should not be needed when test class is in same package as class under test.

2023-11-23 16:45 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/crestdeviceservice/data/CommandLineRunnerDevDatabaseInit.kt
> +        flyway.migrate()
Have you tried adding `@DependsOn({"flyway", "flywayInitializer"})` annotation to the class?

2023-11-23 16:45 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/crestdeviceservice/coap/DownlinkService.kt
> +    }
Probably sufficient for now, but in the (near) future we might also have to handle other downlinks as well...
I'm wondering if it should be the responsibility of the downlink service to check and recreate PSKs...

2023-11-27 11:38 UTC, LucianoFavoroso commented on application/src/integrationTest/kotlin/org/gxf/crestdeviceservice/PskControllerTest.kt
> +    private lateinit var mockMvc: MockMvc
Deze vind ik lastig heb je een suggestie?

2023-11-27 11:57 UTC, LucianoFavoroso commented on application/src/integrationTest/kotlin/org/gxf/crestdeviceservice/PskServiceTest.kt
> +private const val IDENTITY = "identity"
Seems like most of the time the companion object is used. I will place it in companion for now, but we should make a decision for this issue.

2023-11-27 12:00 UTC, LucianoFavoroso commented on application/src/integrationTest/resources/application.yaml
> +    dev-device-identity: "867787050253370" #Should be the same as the identity in the simulator only relevant for dev
I do not know what our plans regarding integration tests are and how spring profiles fit in. For now I suggest to keep it like this and update when needed. Comments on new line is done.

2023-11-27 12:17 UTC, LucianoFavoroso commented on application/src/integrationTest/kotlin/org/gxf/crestdeviceservice/PskControllerTest.kt
> +    private lateinit var mock: PskService
This test is created to test logic in the controller. 
It does 2 things:
- validates that there is a psk endpoint wich accepts requests with the custom header
- validates that the correct status code is returned based on the existence of a return value

Because I used the @WebMvcTest annotation a very limited spring context is created. This context does not include @Component and @Repository beans. So these are mocked.

Using this spring test slice has increased peformance because less of the context is loaded. All the other code should be tested separately. This is done in the PskServiceTest class for example.

This can be a nice subject to discuss.

2023-11-27 12:21 UTC, LucianoFavoroso commented on application/src/main/kotlin/org/gxf/crestdeviceservice/data/entity/PskKey.kt
> +    constructor() : this(null, null)
Sadly yes, it is needed. We can also consider to make it a data class. Spoke with Sander V and this was the conclussion.

2023-12-04 16:54 UTC, smvdheijden requested changes

2023-12-04 16:54 UTC, smvdheijden commented on application/src/integrationTest/kotlin/org/gxf/crestdeviceservice/MessageHandelingTest.kt
> +        assertThat("0").isEqualTo(response.body)
Wrong order of actual and expected values

2023-12-04 16:54 UTC, smvdheijden commented on application/src/integrationTest/kotlin/org/gxf/crestdeviceservice/MessageHandelingTest.kt
> +        assertThat(expectedJsonNode).isEqualTo(payloadJsonNode)
Wrong order of actual and expected values

2023-12-04 16:54 UTC, smvdheijden commented on application/src/integrationTest/kotlin/org/gxf/crestdeviceservice/MessageHandelingTest.kt
>  class MessageHandelingTest {
Fix typo, also rename file.

```suggestion
class MessageHandlingTest {
```

2023-12-04 16:54 UTC, smvdheijden commented on application/src/integrationTest/kotlin/org/gxf/crestdeviceservice/PreSharedKeyRetrieveTest.kt
> +class PreSharedKeyRetrieveTest {
Consider renaming class (and file) to either `RetrievePreSharedKeyTest` or `PreSharedKeyRetrievalTest`

2023-12-04 16:54 UTC, smvdheijden commented on application/src/integrationTest/kotlin/org/gxf/crestdeviceservice/PreSharedKeyRetrieveTest.kt
> +        assertThat("0000111122223333").isEqualTo(result.body)
Switch actual and expected values.

2023-12-04 16:54 UTC, smvdheijden commented on application/src/integrationTest/kotlin/org/gxf/crestdeviceservice/PreSharedKeyRetrieveTest.kt
> +        assertThat(HttpStatus.NOT_FOUND).isEqualTo(result.statusCode)
Switch actual and expected values.

2023-12-04 16:54 UTC, smvdheijden commented on application/src/integrationTest/kotlin/org/gxf/crestdeviceservice/MessageHandelingTest.kt
>      @Value("\${crest-device-service.kafka.message-producer.topic-name}")
Consider using configuration properties instead of using `@Value` annotations directly

2023-12-04 16:54 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/crestdeviceservice/data/entity/PreSharedKey.kt
> +package org.gxf.crestdeviceservice.data.entity
Add license header

2023-12-04 16:54 UTC, smvdheijden commented on application/src/test/kotlin/MeasurementProducerTest.kt
>                  check { assertEquals("topic", it) }, check { assertEquals(jsonNode.toString(), it.payload) })
Use AssertJ assertions

2023-12-04 16:54 UTC, smvdheijden commented on application/src/test/kotlin/org/gxf/crestdeviceservice/coap/DownlinkServiceTest.kt
> +        assertThat("0").isEqualTo(result)
Switch actual and expected values

2023-12-04 16:54 UTC, smvdheijden commented on application/src/test/kotlin/org/gxf/crestdeviceservice/coap/DownlinkServiceTest.kt
> +        assertThat("PSK:key;PSK:keySET").isEqualTo(result)
Switch actual and expected values

2023-12-04 16:54 UTC, smvdheijden commented on application/src/test/kotlin/org/gxf/crestdeviceservice/data/convertors/DatabaseFieldEncryptorTest.kt
> +        assertThat(expected).isEqualTo(decrypted)
Switch actual and expected values.
```suggestion
        assertThat(encrypted).isNotEqualTo("data")
        assertThat(decrypted).isEqualTo(expected)
```

2023-12-04 16:54 UTC, smvdheijden commented on settings.gradle.kts
> +            library("assertJ", "org.assertj", "assertj-core").version("3.24.2")
Isn't the version provided by Spring Boot?

2023-12-04 16:54 UTC, smvdheijden commented on settings.gradle.kts
> +}
Add newline

2023-12-05 10:56 UTC, smvdheijden requested changes

2023-12-05 10:56 UTC, smvdheijden commented on application/src/integrationTest/kotlin/org/gxf/crestdeviceservice/MessageHandlingTest.kt
>      private lateinit var crestMessageTopicName: String
Since the topic name is now retrieved from the configuration properties, this unused field could be removed.

2023-12-05 13:16 UTC, merged