Feature/fdp 2551 command result hander refactoring
OSGP/sng-crest-device-service pull request #74
Opened 2024-11-15 15:48 UTC by smvdheijden

2024-11-19 10:49 UTC, loesimmens requested changes

2024-11-19 14:50 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/crestdeviceservice/command/resulthandler/CommandResultHandler.kt
> +}
New line is present, but not shown? :confused:

2024-11-20 10:51 UTC, levi-h submitted a review, later dismissed

2024-11-20 10:51 UTC, levi-h commented on application/src/main/kotlin/org/gxf/crestdeviceservice/command/entity/Command.kt
> +    enum class CommandType(val downlink: String, val needsCommandValue: Boolean = false) {
Would it be possible to move the command value check to the handler (so that this boolean is no longer necessary)?

2024-11-20 10:51 UTC, levi-h commented on application/src/main/kotlin/org/gxf/crestdeviceservice/command/resulthandler/CommandResultHandler.kt
> +
I don't find that the empty line at the start of a class (or a function or any block, really) improves readability - I understand it's a matter of taste but it's good to have consistency, I think

2024-11-20 10:51 UTC, levi-h commented on application/src/main/kotlin/org/gxf/crestdeviceservice/command/resulthandler/CommandResultHandler.kt
> +    abstract fun forCommandType(): CommandType
would `supportedCommandType` be a more descriptive name? And could this be a val instead of a function?

2024-11-20 10:51 UTC, levi-h commented on application/src/main/kotlin/org/gxf/crestdeviceservice/command/resulthandler/FirmwareCommandResultHandler.kt
> +    private fun containsSuccessUrc(body: JsonNode) = getUrcsFromMessage(body).contains(succesUrc)
The `in` operator could be used here

2024-11-20 10:51 UTC, levi-h commented on application/src/main/kotlin/org/gxf/crestdeviceservice/command/resulthandler/CommandResultHandler.kt
> +    fun getUrcsFromMessage(body: JsonNode) = body[URC_FIELD].filter { it.isTextual }.map { it.asText() }
I would like this as an extension method/property, then the invocations could look like `body.urcs` (or urcsFromMessage)

2024-11-20 10:51 UTC, levi-h commented on application/src/main/kotlin/org/gxf/crestdeviceservice/command/service/CommandResultService.kt
> +    private val commandResultHandlersMap: EnumMap<Command.CommandType, CommandResultHandler> by lazy { initMap() }
I would drop this map and just lookup the handler every time it's needed

2024-11-20 10:51 UTC, levi-h commented on application/src/main/kotlin/org/gxf/crestdeviceservice/command/service/CommandResultService.kt
> +            Command.CommandType.entries.associateWith { entry ->
... but if you decide to keep te map, I'd rename `entry` to `commandType` here (and probably rename the field to `commandResultHandlersByType`)

2024-11-20 10:51 UTC, levi-h commented on application/src/test/kotlin/org/gxf/crestdeviceservice/command/resulthandler/FirmwareCommandResultHandlerTest.kt
> +        // arrange
I think the tests would be as readable without these comments

2024-11-20 10:51 UTC, levi-h commented on application/src/test/kotlin/org/gxf/crestdeviceservice/command/resulthandler/FirmwareCommandResultHandlerTest.kt
> +        assertThat(command.status == Command.CommandStatus.SUCCESSFUL)
Here, `.isTrue()` seems to be missing

2024-11-20 10:51 UTC, levi-h commented on application/src/test/kotlin/org/gxf/crestdeviceservice/command/resulthandler/PskCommandResultHandlerTest.kt
> +        assertThat(command.status == Command.CommandStatus.SUCCESSFUL)
I'd prefer `isEqualTo`/`isSameAs` I think

2024-11-20 10:51 UTC, levi-h commented on application/src/test/kotlin/org/gxf/crestdeviceservice/command/service/CommandResultServiceTest.kt
> +    private lateinit var commandResultHandlers: List<CommandResultHandler>
Are these used outside of the setUp method?

2024-11-21 10:03 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/crestdeviceservice/command/entity/Command.kt
> +    enum class CommandType(val downlink: String, val needsCommandValue: Boolean = false) {
I don't think so as the handler only checks the resulting message, after the command including the value has already been sent to the device in a downlink.

2024-11-21 10:18 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/crestdeviceservice/command/resulthandler/CommandResultHandler.kt
> +
In this case you're probably right, though I think it might depend on the (formatting of the) class definition itself?

In the example below I think I would prefer the empty line, since the indentation of the second line at the start of the class would be the same as the next line in the class:

```kotlin
class RebootCommandResultHandler(commandService: CommandService, commandFeedbackService: CommandFeedbackService) :
    CommandResultHandler(commandService, commandFeedbackService) {

    private val succesUrcs = listOf("INIT", "WDR")
```

2024-11-21 13:37 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/crestdeviceservice/command/resulthandler/CommandResultHandler.kt
> +    abstract fun forCommandType(): CommandType
I think the name was ok as it denotes it is the handler **for** this type of command.
Refactored it nevertheless, since `supportedCommandType` is also fine by me.

2024-11-21 13:38 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/crestdeviceservice/command/resulthandler/CommandResultHandler.kt
> +    fun getUrcsFromMessage(body: JsonNode) = body[URC_FIELD].filter { it.isTextual }.map { it.asText() }
Spotless doesn't seem to like the extension properties. Refactored them in extension methods.

2024-11-21 13:38 UTC, smvdheijden commented on application/src/main/kotlin/org/gxf/crestdeviceservice/command/service/CommandResultService.kt
> +    private val commandResultHandlersMap: EnumMap<Command.CommandType, CommandResultHandler> by lazy { initMap() }
I've refactored the code so that the map (instead of the list) will be autowired into this class.

2024-11-22 10:48 UTC, Tortoaster approved these changes

2024-11-22 14:51 UTC, merged